### ISSUE TITLE
Evaluating any program fails with a match failure in FunDef load rule.

### ISSUE THREAD

**Issue by Balletie** [MetaBorgCube/metaborg-sl#1]
It appears it goes wrong at the `FunDef/load/3` rule: https://github.com/MetaBorgCube/metaborg-sl/blob/master/org.metaborg.lang.sl/trans/semantics/functions.ds#L33-L35.

This is on the latest master of metaborg/dynsem, commit 9f73044.

The java stacktrace (this one is of the program under "src/test/resources/LoopPolymorphic.sl"):

```
Exception in thread "main" com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for MapExtendBuildNodeGen@1f97cf0d: [{"add" FunV_3(add,("a" "b"),__Block2Stmt___1(Block_1((Return_1(Add_2(VarRead_1(a)@c333c60,VarRead_1(b)@79da8dc5)@1eb5174b)@67080771))@72cde7cc)@5fd4f8f5)@696da30b}, C_1({})@53976f5c], [PersistentHashMap,C_1_Term]
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.building.MapExtendBuildNodeGen.unsupported(MapExtendBuildNodeGen.java:56)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.building.MapExtendBuildNodeGen.executeGeneric(MapExtendBuildNodeGen.java:46)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleTarget.execute(RuleTarget.java:36)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:55)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DynamicRelationDispatch$_Monomorphic.execute(DynamicRelationDispatch.java:68)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DynamicRelationDispatch$_Uninitialized.execute(DynamicRelationDispatch.java:43)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.RelationInvocationNode.execute(RelationInvocationNode.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.Case$CasePattern.execute(Case.java:88)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.CaseMatchPremise.execute(CaseMatchPremise.java:36)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:62)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:52)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RecursiveReductionRule.execute(RecursiveReductionRule.java:30)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.RelationDispatch$InlinedRelationDispatch.execute(RelationDispatch.java:109)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.RelationDispatch$ListRelationDispatch.execute(RelationDispatch.java:92)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.RelationInvocationNode.execute(RelationInvocationNode.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:62)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:52)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleRoot.execute(RuleRoot.java:22)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleRoot.execute(RuleRoot.java:1)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at org.metaborg.meta.lang.dynsem.interpreter.DynSemRunForeignAccess$DynSemForeignCallerRootNode.execute(DynSemRunForeignAccess.java:56)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:69)
    at com.oracle.truffle.api.interop.CachedObjectAccessNode.doAccess(CachedObjectAccessNode.java:55)
    at com.oracle.truffle.api.interop.CachedObjectAccessNode.executeWith(CachedObjectAccessNode.java:50)
    at com.oracle.truffle.api.interop.UnresolvedObjectAccessNode.executeWith(UnresolvedObjectAccessNode.java:45)
    at com.oracle.truffle.api.interop.ForeignObjectAccessHeadNode.executeForeignImpl(ForeignObjectAccessHeadNode.java:59)
    at com.oracle.truffle.api.interop.ForeignAccess.send(ForeignAccess.java:119)
    at com.oracle.truffle.api.vm.SymbolInvokerImpl$TemporaryRoot.execute(SymbolInvokerImpl.java:87)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.vm.PolyglotEngine$Value$2.compute(PolyglotEngine.java:737)
    at com.oracle.truffle.api.vm.ComputeInExecutor.run(ComputeInExecutor.java:93)
    at com.oracle.truffle.api.vm.ComputeInExecutor.perform(ComputeInExecutor.java:83)
    at com.oracle.truffle.api.vm.PolyglotEngine$Value.execute(PolyglotEngine.java:745)
    at org.metaborg.lang.sl.interpreter.generated.SLLanguage$1.call(SLLanguage.java:98)
    at org.metaborg.lang.sl.interpreter.generated.SLLanguage$1.call(SLLanguage.java:1)
    at org.metaborg.lang.sl.interpreter.generated.SLLanguage.evaluate(SLLanguage.java:78)
    at org.metaborg.lang.sl.interpreter.generated.SLLanguage.main(SLLanguage.java:72)
```

**Comment by vvergu** [comment]
Fixed.
